package main

import (
	"time"

	"github.com/janekbaraniewski/openusage/internal/core"
)

func buildCodexDemoSnapshot(now time.Time) core.UsageSnapshot {
	return core.UsageSnapshot{
		ProviderID: "codex",
		AccountID:  "codex-cli",
		Timestamp:  now,
		Status:     core.StatusLimited,
		Metrics: map[string]core.Metric{
			"rate_limit_primary":               {Used: ptr(18), Limit: ptr(100), Remaining: ptr(82), Unit: "%", Window: "5h"},
			"rate_limit_secondary":             {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"rate_limit_code_review_primary":   {Used: ptr(2), Limit: ptr(100), Remaining: ptr(98), Unit: "%", Window: "7d"},
			"rate_limit_code_review_secondary": {Used: ptr(0), Limit: ptr(100), Remaining: ptr(100), Unit: "%", Window: "7d"},
			"plan_auto_percent_used":           {Used: ptr(18), Limit: ptr(100), Remaining: ptr(82), Unit: "%", Window: "5h"},
			"plan_api_percent_used":            {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"plan_percent_used":                {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"context_window":                   {Used: ptr(10400000), Limit: ptr(258400), Unit: "tokens"},
			"composer_context_pct":             {Used: ptr(100), Unit: "%", Window: "all-time"},
			"credit_balance":                   {Used: ptr(42.6), Unit: "USD", Window: "current"},
			"session_cached_tokens":            {Used: ptr(7320000), Unit: "tokens", Window: "session"},
			"session_input_tokens":             {Used: ptr(10800), Unit: "tokens", Window: "session"},
			"session_output_tokens":            {Used: ptr(121300), Unit: "tokens", Window: "session"},
			"session_reasoning_tokens":         {Used: ptr(40600), Unit: "tokens", Window: "session"},
			"session_total_tokens":             {Used: ptr(10500000), Unit: "tokens", Window: "session"},

			"model_gpt_5_3_codex_input_tokens":          {Used: ptr(1940000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_3_codex_output_tokens":         {Used: ptr(398000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_3_codex_cached_tokens":         {Used: ptr(60000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_3_codex_reasoning_tokens":      {Used: ptr(90000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_3_codex_total_tokens":          {Used: ptr(2388000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_max_input_tokens":      {Used: ptr(102000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_max_output_tokens":     {Used: ptr(15000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_max_cached_tokens":     {Used: ptr(12000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_max_reasoning_tokens":  {Used: ptr(4000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_max_total_tokens":      {Used: ptr(133000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_2_codex_input_tokens":          {Used: ptr(86000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_2_codex_output_tokens":         {Used: ptr(11000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_2_codex_cached_tokens":         {Used: ptr(2800), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_2_codex_reasoning_tokens":      {Used: ptr(900), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_2_codex_total_tokens":          {Used: ptr(100700), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_mini_input_tokens":     {Used: ptr(60000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_mini_output_tokens":    {Used: ptr(7000), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_mini_cached_tokens":    {Used: ptr(1500), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_mini_reasoning_tokens": {Used: ptr(300), Unit: "tokens", Window: "all-time"},
			"model_gpt_5_1_codex_mini_total_tokens":     {Used: ptr(68800), Unit: "tokens", Window: "all-time"},

			"client_cli_total_tokens":          {Used: ptr(6200000), Unit: "tokens", Window: "all-time"},
			"client_cli_input_tokens":          {Used: ptr(5100000), Unit: "tokens", Window: "all-time"},
			"client_cli_output_tokens":         {Used: ptr(980000), Unit: "tokens", Window: "all-time"},
			"client_cli_cached_tokens":         {Used: ptr(91000), Unit: "tokens", Window: "all-time"},
			"client_cli_reasoning_tokens":      {Used: ptr(29000), Unit: "tokens", Window: "all-time"},
			"client_cli_sessions":              {Used: ptr(44), Unit: "sessions", Window: "all-time"},
			"client_cli_requests":              {Used: ptr(5100), Unit: "requests", Window: "all-time"},
			"client_desktop_app_total_tokens":  {Used: ptr(3600000), Unit: "tokens", Window: "all-time"},
			"client_desktop_app_input_tokens":  {Used: ptr(2910000), Unit: "tokens", Window: "all-time"},
			"client_desktop_app_output_tokens": {Used: ptr(610000), Unit: "tokens", Window: "all-time"},
			"client_desktop_app_cached_tokens": {Used: ptr(62000), Unit: "tokens", Window: "all-time"},
			"client_desktop_app_sessions":      {Used: ptr(31), Unit: "sessions", Window: "all-time"},
			"client_desktop_app_requests":      {Used: ptr(3700), Unit: "requests", Window: "all-time"},
			"client_ide_total_tokens":          {Used: ptr(2100000), Unit: "tokens", Window: "all-time"},
			"client_ide_input_tokens":          {Used: ptr(1700000), Unit: "tokens", Window: "all-time"},
			"client_ide_output_tokens":         {Used: ptr(350000), Unit: "tokens", Window: "all-time"},
			"client_ide_cached_tokens":         {Used: ptr(40000), Unit: "tokens", Window: "all-time"},
			"client_ide_reasoning_tokens":      {Used: ptr(10000), Unit: "tokens", Window: "all-time"},
			"client_ide_sessions":              {Used: ptr(14), Unit: "sessions", Window: "all-time"},
			"client_ide_requests":              {Used: ptr(1400), Unit: "requests", Window: "all-time"},
			"client_cloud_agents_total_tokens": {Used: ptr(740000), Unit: "tokens", Window: "all-time"},
			"client_cloud_agents_requests":     {Used: ptr(620), Unit: "requests", Window: "all-time"},
			"client_cloud_agents_sessions":     {Used: ptr(6), Unit: "sessions", Window: "all-time"},

			"interface_cli_agents":   {Used: ptr(5100), Unit: "requests", Window: "all-time"},
			"interface_desktop_app":  {Used: ptr(3700), Unit: "requests", Window: "all-time"},
			"interface_ide":          {Used: ptr(1400), Unit: "requests", Window: "all-time"},
			"interface_cloud_agents": {Used: ptr(620), Unit: "requests", Window: "all-time"},

			"tool_exec_command":   {Used: ptr(10100), Unit: "calls", Window: "all-time"},
			"tool_apply_patch":    {Used: ptr(2300), Unit: "calls", Window: "all-time"},
			"tool_shell_command":  {Used: ptr(936), Unit: "calls", Window: "all-time"},
			"tool_web_search":     {Used: ptr(524), Unit: "calls", Window: "all-time"},
			"tool_write_stdin":    {Used: ptr(353), Unit: "calls", Window: "all-time"},
			"tool_update_plan":    {Used: ptr(51), Unit: "calls", Window: "all-time"},
			"tool_open":           {Used: ptr(19), Unit: "calls", Window: "all-time"},
			"tool_find":           {Used: ptr(17), Unit: "calls", Window: "all-time"},
			"tool_click":          {Used: ptr(13), Unit: "calls", Window: "all-time"},
			"tool_screenshot":     {Used: ptr(9), Unit: "calls", Window: "all-time"},
			"tool_image_query":    {Used: ptr(8), Unit: "calls", Window: "all-time"},
			"tool_go_test":        {Used: ptr(7), Unit: "calls", Window: "all-time"},
			"tool_gofmt":          {Used: ptr(6), Unit: "calls", Window: "all-time"},
			"tool_mcp_gopls":      {Used: ptr(4), Unit: "calls", Window: "all-time"},
			"tool_mcp_kubernetes": {Used: ptr(3), Unit: "calls", Window: "all-time"},
			"tool_mcp_linear":     {Used: ptr(2), Unit: "calls", Window: "all-time"},

			// ── MCP servers ───────────────────────────────────────
			"mcp_calls_total":       {Used: ptr(384), Unit: "calls", Window: "all-time"},
			"mcp_calls_total_today": {Used: ptr(52), Unit: "calls", Window: "1d"},
			"mcp_servers_active":    {Used: ptr(3), Unit: "servers", Window: "all-time"},

			"mcp_gopls_total":           {Used: ptr(218), Unit: "calls", Window: "all-time"},
			"mcp_gopls_total_today":     {Used: ptr(34), Unit: "calls", Window: "1d"},
			"mcp_gopls_go_diagnostics":  {Used: ptr(92), Unit: "calls", Window: "all-time"},
			"mcp_gopls_go_file_context": {Used: ptr(74), Unit: "calls", Window: "all-time"},
			"mcp_gopls_go_search":       {Used: ptr(52), Unit: "calls", Window: "all-time"},

			"mcp_kubernetes_total":          {Used: ptr(98), Unit: "calls", Window: "all-time"},
			"mcp_kubernetes_total_today":    {Used: ptr(12), Unit: "calls", Window: "1d"},
			"mcp_kubernetes_get_pods":       {Used: ptr(42), Unit: "calls", Window: "all-time"},
			"mcp_kubernetes_apply_manifest": {Used: ptr(31), Unit: "calls", Window: "all-time"},
			"mcp_kubernetes_get_logs":       {Used: ptr(25), Unit: "calls", Window: "all-time"},

			"mcp_linear_total":       {Used: ptr(68), Unit: "calls", Window: "all-time"},
			"mcp_linear_total_today": {Used: ptr(6), Unit: "calls", Window: "1d"},
			"mcp_linear_list_issues": {Used: ptr(32), Unit: "calls", Window: "all-time"},
			"mcp_linear_save_issue":  {Used: ptr(22), Unit: "calls", Window: "all-time"},
			"mcp_linear_get_issue":   {Used: ptr(14), Unit: "calls", Window: "all-time"},

			"tool_calls_total":  {Used: ptr(14352), Unit: "calls", Window: "all-time"},
			"tool_completed":    {Used: ptr(13060), Unit: "calls", Window: "all-time"},
			"tool_errored":      {Used: ptr(1060), Unit: "calls", Window: "all-time"},
			"tool_cancelled":    {Used: ptr(232), Unit: "calls", Window: "all-time"},
			"tool_success_rate": {Used: ptr(91), Unit: "%", Window: "all-time"},

			"lang_go":        {Used: ptr(1300), Unit: "requests", Window: "all-time"},
			"lang_ts":        {Used: ptr(400), Unit: "requests", Window: "all-time"},
			"lang_shell":     {Used: ptr(153), Unit: "requests", Window: "all-time"},
			"lang_md":        {Used: ptr(148), Unit: "requests", Window: "all-time"},
			"lang_yaml":      {Used: ptr(76), Unit: "requests", Window: "all-time"},
			"lang_json":      {Used: ptr(23), Unit: "requests", Window: "all-time"},
			"lang_python":    {Used: ptr(18), Unit: "requests", Window: "all-time"},
			"lang_terraform": {Used: ptr(9), Unit: "requests", Window: "all-time"},

			"total_ai_requests":       {Used: ptr(10200), Unit: "requests", Window: "all-time"},
			"composer_requests":       {Used: ptr(10200), Unit: "requests", Window: "all-time"},
			"requests_today":          {Used: ptr(150), Unit: "requests", Window: "today"},
			"today_composer_requests": {Used: ptr(150), Unit: "requests", Window: "today"},
			"composer_sessions":       {Used: ptr(89), Unit: "sessions", Window: "all-time"},
			"total_prompts":           {Used: ptr(572), Unit: "prompts", Window: "all-time"},
			"composer_lines_added":    {Used: ptr(73300), Unit: "lines", Window: "all-time"},
			"composer_lines_removed":  {Used: ptr(17400), Unit: "lines", Window: "all-time"},
			"composer_files_changed":  {Used: ptr(639), Unit: "files", Window: "all-time"},
			"scored_commits":          {Used: ptr(14), Unit: "commits", Window: "all-time"},
			"ai_code_percentage":      {Used: ptr(22), Unit: "%", Window: "all-time"},
			"ai_deleted_files":        {Used: ptr(50), Unit: "files", Window: "all-time"},
			"ai_tracked_files":        {Used: ptr(639), Unit: "files", Window: "all-time"},
		},
		Resets: map[string]time.Time{
			"rate_limit_primary":               now.Add(4*time.Hour + 59*time.Minute),
			"rate_limit_secondary":             now.Add(3*24*time.Hour + 20*time.Hour),
			"rate_limit_code_review_primary":   now.Add(7 * 24 * time.Hour),
			"rate_limit_code_review_secondary": now.Add(7 * 24 * time.Hour),
		},
		Raw: map[string]string{
			"account_email":  "anon.codex.user@example.invalid",
			"account_id":     "anon-codex-team-01",
			"plan_type":      "team",
			"cli_version":    "0.105.0",
			"credit_balance": "$42.60",
			"model_usage":    "gpt-5-3-codex 94%, gpt-5-1-codex-max 5%, gpt-5-2-codex 1%, gpt-5-1-codex-mini 1%",
			"client_usage":   "CLI Agents 50%, Desktop App 36%, IDE 13%, Cloud Agents 6%",
			"tool_usage":     "exec_command 70%, apply_patch 16%, shell_command 7%, web_search 4%, write_stdin 2%, update_plan 0%",
			"language_usage": "go 61%, ts 19%, shell 7%, md 7%, yaml 4%, json 1%",
		},
		DailySeries: map[string][]core.TimePoint{
			"tokens_client_cli":              demoSeries(now, 1010000, 1040000, 1090000, 1120000, 1170000, 1220000, 1280000),
			"tokens_client_desktop_app":      demoSeries(now, 730000, 760000, 800000, 830000, 880000, 910000, 940000),
			"tokens_client_ide":              demoSeries(now, 240000, 260000, 280000, 310000, 330000, 350000, 370000),
			"usage_model_gpt_5_3_codex":      demoSeries(now, 305000, 321000, 332000, 346000, 362000, 380000, 395000),
			"usage_model_gpt_5_1_codex_max":  demoSeries(now, 12000, 14000, 16000, 17000, 19000, 22000, 23000),
			"usage_model_gpt_5_2_codex":      demoSeries(now, 9000, 9800, 10200, 10900, 11300, 11900, 12600),
			"usage_model_gpt_5_1_codex_mini": demoSeries(now, 6000, 7000, 7600, 8200, 9100, 9800, 10600),
			"usage_client_cli_agents":        demoSeries(now, 640, 690, 710, 760, 790, 840, 890),
			"usage_client_desktop_app":       demoSeries(now, 420, 450, 480, 520, 560, 600, 640),
			"usage_client_ide":               demoSeries(now, 180, 210, 230, 250, 280, 300, 320),
			"usage_client_cloud_agents":      demoSeries(now, 80, 85, 92, 98, 101, 110, 118),
			"usage_source_cli_agents":        demoSeries(now, 640, 690, 710, 760, 790, 840, 890),
			"usage_source_desktop_app":       demoSeries(now, 420, 450, 480, 520, 560, 600, 640),
			"usage_source_ide":               demoSeries(now, 180, 210, 230, 250, 280, 300, 320),
			"usage_source_cloud_agents":      demoSeries(now, 80, 85, 92, 98, 101, 110, 118),
			"analytics_tokens":               demoSeries(now, 1730000, 1820000, 1890000, 2010000, 2140000, 2280000, 2410000),
			"tokens_total":                   demoSeries(now, 1730000, 1820000, 1890000, 2010000, 2140000, 2280000, 2410000),
			"analytics_requests":             demoSeries(now, 1320, 1435, 1512, 1628, 1731, 1850, 1968),
			"requests":                       demoSeries(now, 1320, 1435, 1512, 1628, 1731, 1850, 1968),
		},
		Message: "Codex live usage + local session data",
	}
}
